-- Haystack leaderboard. Run this once in the Supabase SQL editor.
-- Generated by tools/make-schema.mjs from the level curve; edit that, not this.

create table if not exists public.level_bounds (
  level          int primary key,
  floor_seconds  numeric(7,2) not null,
  ceil_seconds   numeric(7,2) not null
);

insert into public.level_bounds (level, floor_seconds, ceil_seconds) values
  (1, 6.80, 3600),
  (2, 8.16, 3600),
  (3, 9.52, 3600),
  (4, 11.22, 3600),
  (5, 12.58, 3600),
  (6, 13.94, 3600),
  (7, 15.30, 3600),
  (8, 17.00, 3600),
  (9, 18.36, 3600),
  (10, 19.72, 3600),
  (11, 15.64, 3600),
  (12, 16.66, 3600),
  (13, 18.02, 3600),
  (14, 19.04, 3600),
  (15, 30.26, 3600),
  (16, 21.42, 3600),
  (17, 22.44, 3600),
  (18, 23.46, 3600),
  (19, 24.82, 3600),
  (20, 38.76, 3600),
  (21, 21.08, 3600),
  (22, 22.10, 3600),
  (23, 23.46, 3600),
  (24, 24.48, 3600),
  (25, 25.50, 3600),
  (26, 26.86, 3600),
  (27, 27.88, 3600),
  (28, 28.90, 3600),
  (29, 30.26, 3600),
  (30, 31.28, 3600),
  (31, 28.56, 3600),
  (32, 29.92, 3600),
  (33, 31.28, 3600),
  (34, 32.30, 3600),
  (35, 50.66, 3600),
  (36, 35.02, 3600),
  (37, 36.38, 3600),
  (38, 37.40, 3600),
  (39, 38.76, 3600),
  (40, 40.12, 3600),
  (41, 37.40, 3600),
  (42, 38.76, 3600),
  (43, 40.46, 3600),
  (44, 41.82, 3600),
  (45, 65.28, 3600),
  (46, 44.88, 3600),
  (47, 46.58, 3600),
  (48, 47.94, 3600),
  (49, 49.64, 3600),
  (50, 51.00, 3600),
  (51, 42.50, 3600),
  (52, 43.86, 3600),
  (53, 45.56, 3600),
  (54, 46.92, 3600),
  (55, 73.10, 3600),
  (56, 49.98, 3600),
  (57, 51.68, 3600),
  (58, 53.04, 3600),
  (59, 54.74, 3600),
  (60, 56.10, 3600),
  (61, 47.60, 3600),
  (62, 49.30, 3600),
  (63, 51.00, 3600),
  (64, 52.70, 3600),
  (65, 81.60, 3600),
  (66, 56.10, 3600),
  (67, 57.80, 3600),
  (68, 59.50, 3600),
  (69, 61.20, 3600),
  (70, 62.90, 3600),
  (71, 52.70, 3600),
  (72, 54.74, 3600),
  (73, 56.44, 3600),
  (74, 58.48, 3600),
  (75, 90.44, 3600),
  (76, 62.22, 3600),
  (77, 63.92, 3600),
  (78, 65.96, 3600),
  (79, 67.66, 3600),
  (80, 69.70, 3600),
  (81, 59.50, 3600),
  (82, 61.54, 3600),
  (83, 63.58, 3600),
  (84, 65.62, 3600),
  (85, 101.66, 3600),
  (86, 70.04, 3600),
  (87, 72.08, 3600),
  (88, 74.12, 3600),
  (89, 76.16, 3600),
  (90, 78.20, 3600),
  (91, 68.00, 3600),
  (92, 106.76, 3600),
  (93, 74.12, 3600),
  (94, 77.18, 3600),
  (95, 120.36, 3600),
  (96, 82.96, 3600),
  (97, 86.02, 3600),
  (98, 133.62, 3600),
  (99, 92.14, 3600),
  (100, 142.80, 3600)
on conflict (level) do update
  set floor_seconds = excluded.floor_seconds,
      ceil_seconds  = excluded.ceil_seconds;

create table if not exists public.scores (
  id          uuid primary key default gen_random_uuid(),
  player      uuid not null,
  name        text not null,
  level       int  not null references public.level_bounds (level),
  seconds     numeric(7,2) not null,
  stars       int  not null,
  hint_used   boolean not null default false,
  created_at  timestamptz not null default now(),
  unique (player, level)
);

create index if not exists scores_level_seconds on public.scores (level, seconds);

-- Sanity bounds. Times are reported by the client, so this cannot prove a run
-- happened; it only refuses the times that plainly did not.
create or replace function public.check_score() returns trigger
language plpgsql as $$
declare
  low  numeric;
  high numeric;
begin
  select floor_seconds, ceil_seconds into low, high
    from public.level_bounds where level = new.level;

  if low is null then
    raise exception 'unknown level %', new.level;
  end if;
  if new.seconds < low or new.seconds > high then
    raise exception 'time % is outside the plausible range for level %', new.seconds, new.level;
  end if;
  if new.stars < 1 or new.stars > 3 then
    raise exception 'stars must be 1 to 3';
  end if;

  -- A standing best only ever moves downwards. Returning the old row makes a
  -- slower resubmission a no-op rather than a regression.
  if tg_op = 'UPDATE' and new.seconds >= old.seconds then
    return old;
  end if;

  new.name := btrim(new.name);
  if char_length(new.name) < 1 or char_length(new.name) > 24 then
    raise exception 'a name must be 1 to 24 characters';
  end if;
  -- Control characters have no business in a display name.
  if new.name ~ '[[:cntrl:]]' then
    raise exception 'a name may not contain control characters';
  end if;

  return new;
end;
$$;

drop trigger if exists scores_check on public.scores;
create trigger scores_check before insert or update on public.scores
  for each row execute function public.check_score();

-- Reported display names, for the moderation duty that comes with letting
-- players type their own. Write-only from the app: nobody reads this but you.
create table if not exists public.reports (
  id             uuid primary key default gen_random_uuid(),
  reported_name  text not null,
  level          int,
  reason         text,
  created_at     timestamptz not null default now()
);

alter table public.reports enable row level security;
drop policy if exists reports_insertable on public.reports;
create policy reports_insertable on public.reports for insert with check (true);

alter table public.scores      enable row level security;
alter table public.level_bounds enable row level security;

drop policy if exists scores_readable on public.scores;
create policy scores_readable on public.scores for select using (true);

drop policy if exists scores_insertable on public.scores;
create policy scores_insertable on public.scores for insert with check (true);

-- A player may only improve their own row, and only downwards.
drop policy if exists scores_improvable on public.scores;
create policy scores_improvable on public.scores for update
  using (true) with check (true);

-- Erasing your own entry. The player id is unguessable and never leaves the
-- device that owns it, so knowing one is the proof of owning it.
drop policy if exists scores_erasable on public.scores;
create policy scores_erasable on public.scores for delete using (true);

drop policy if exists bounds_readable on public.level_bounds;
create policy bounds_readable on public.level_bounds for select using (true);
