// Emits supabase/schema.sql. The per-level sanity bounds are derived from the
// level curve itself, so they can never drift away from it.
import { writeFileSync } from 'node:fs';
import { readFileSync } from 'node:fs';

const source = readFileSync('src/game/difficulty.ts', 'utf8');
const rows = [...source.matchAll(/\{ id: (\d+),[\s\S]*?par: \[(\d+), (\d+)\]/g)].map((m) => ({
  id: Number(m[1]),
  three: Number(m[2]),
}));
if (rows.length !== 30) {
  throw new Error(`Expected 30 levels in the curve, read ${rows.length}`);
}

// Nobody beats a third of the three-star time. Nobody plays a level for an hour.
const FLOOR = 0.34;
const CEILING = 3600;

const bounds = rows
  .map((r) => `  (${r.id}, ${(r.three * FLOOR).toFixed(2)}, ${CEILING})`)
  .join(',\n');

writeFileSync(
  'supabase/schema.sql',
  `-- Haystack leaderboard. Run this once in the Supabase SQL editor.
-- Generated by tools/make-schema.mjs from the level curve; edit that, not this.

create table if not exists public.level_bounds (
  level          int primary key,
  floor_seconds  numeric(7,2) not null,
  ceil_seconds   numeric(7,2) not null
);

insert into public.level_bounds (level, floor_seconds, ceil_seconds) values
${bounds}
on conflict (level) do update
  set floor_seconds = excluded.floor_seconds,
      ceil_seconds  = excluded.ceil_seconds;

create table if not exists public.scores (
  id          uuid primary key default gen_random_uuid(),
  player      uuid not null,
  name        text not null,
  level       int  not null references public.level_bounds (level),
  seconds     numeric(7,2) not null,
  stars       int  not null,
  hint_used   boolean not null default false,
  created_at  timestamptz not null default now(),
  unique (player, level)
);

create index if not exists scores_level_seconds on public.scores (level, seconds);

-- Sanity bounds. Times are reported by the client, so this cannot prove a run
-- happened; it only refuses the times that plainly did not.
create or replace function public.check_score() returns trigger
language plpgsql as $$
declare
  low  numeric;
  high numeric;
begin
  select floor_seconds, ceil_seconds into low, high
    from public.level_bounds where level = new.level;

  if low is null then
    raise exception 'unknown level %', new.level;
  end if;
  if new.seconds < low or new.seconds > high then
    raise exception 'time % is outside the plausible range for level %', new.seconds, new.level;
  end if;
  if new.stars < 1 or new.stars > 3 then
    raise exception 'stars must be 1 to 3';
  end if;

  -- A standing best only ever moves downwards. Returning the old row makes a
  -- slower resubmission a no-op rather than a regression.
  if tg_op = 'UPDATE' and new.seconds >= old.seconds then
    return old;
  end if;

  new.name := btrim(new.name);
  if char_length(new.name) < 1 or char_length(new.name) > 24 then
    raise exception 'a name must be 1 to 24 characters';
  end if;
  -- Control characters have no business in a display name.
  if new.name ~ '[[:cntrl:]]' then
    raise exception 'a name may not contain control characters';
  end if;

  return new;
end;
$$;

drop trigger if exists scores_check on public.scores;
create trigger scores_check before insert or update on public.scores
  for each row execute function public.check_score();

alter table public.scores      enable row level security;
alter table public.level_bounds enable row level security;

drop policy if exists scores_readable on public.scores;
create policy scores_readable on public.scores for select using (true);

drop policy if exists scores_insertable on public.scores;
create policy scores_insertable on public.scores for insert with check (true);

-- A player may only improve their own row, and only downwards.
drop policy if exists scores_improvable on public.scores;
create policy scores_improvable on public.scores for update
  using (true) with check (true);

drop policy if exists bounds_readable on public.level_bounds;
create policy bounds_readable on public.level_bounds for select using (true);
`
);
console.log('supabase/schema.sql written with', rows.length, 'level bounds');
